/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { HexTerrain } from '../../types'
import { hexTerrainColor } from '../maphex/hexColors'

export function Battlement() {
  const { nodes } = useGLTF('/handmade-battlement.glb') as any
  return (
    <mesh
      geometry={nodes.Battlement.geometry}
    >
      <meshMatcapMaterial color={hexTerrainColor[HexTerrain.battlement]} />
    </mesh>
  )
}

useGLTF.preload('/handmade-battlement.glb')
