/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { BoardHex } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import { HEXGRID_HEX_HEIGHT, HEXGRID_HEX_RADIUS, TREE_BASE_HEIGHT } from '../../utils/constants'
import ForestTreeBase from './ForestTreeBase'

export default function BigTree415({ boardHex }: { boardHex: BoardHex }) {
  const { x, z } = getBoardHex3DCoords(boardHex)
  const y = (boardHex.altitude - 1) * HEXGRID_HEX_HEIGHT
  const yTree = y + TREE_BASE_HEIGHT / 2
  const yBase = y + TREE_BASE_HEIGHT / 2
  const { nodes, materials } = useGLTF('/forest-tree15-colored-lowpoly.glb') as any
  const xLength = Math.cos(Math.PI / 6) * 1.5
  const zLength = Math.sin(Math.PI / 6) * 1.5
  const options = getOptionsForBigTree(boardHex.pieceRotation)
  function getOptionsForBigTree(rotation: number) {
    switch (rotation) {
      case 0:
        return { rotationY: Math.PI / 3, xAdd: xLength, zAdd: zLength }
      case 1:
        return { rotationY: 0, xAdd: 0, zAdd: 1.5 * HEXGRID_HEX_RADIUS }
      case 2:
        return { rotationY: -Math.PI / 3, xAdd: -xLength, zAdd: zLength }
      case 3:
        return { rotationY: Math.PI / 3, xAdd: -xLength, zAdd: -zLength }
      case 4:
        return { rotationY: 0, xAdd: 0, zAdd: -1.5 * HEXGRID_HEX_RADIUS }
      case 5:
        return { rotationY: -Math.PI / 3, xAdd: xLength, zAdd: -zLength }
      default:
        return { rotationY: 0, xAdd: 0, zAdd: 0 }
    }
  }
  if (boardHex.isAuxiliary) {
    return (
      <ForestTreeBase x={x} y={yBase} z={z} />
    )
  }
  return (
    <group dispose={null}>
      <group
        position={[x + options.xAdd, yTree, z + options.zAdd]}
        // position={[x, yTree, z]}
        scale={0.038}
        rotation={[0, options.rotationY, 0]}
        castShadow
        receiveShadow
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_large_rocks_scanned001_1.geometry}
          material={materials.BoulderGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_large_rocks_scanned001_2.geometry}
          material={materials.ForestTree}
        />
      </group>
      <ForestTreeBase x={x} y={yBase} z={z} />
    </group>

  )
}

useGLTF.preload('/forest-tree15-colored-lowpoly.glb')