/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { BoardHex } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'

export default function BigTree415({ boardHex }: { boardHex: BoardHex }) {
  const { x, y, z } = getBoardHex3DCoords(boardHex)
  const { nodes, materials } = useGLTF('/forest-tree15-colored-lowpoly.glb') as any
  return (
    <group position={[x, y, z]} dispose={null}>
      <group scale={0.038}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_large_rocks_scanned001_1.geometry}
          material={materials.BoulderGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_large_rocks_scanned001_2.geometry}
          material={materials.ForestTree}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/forest-tree15-colored-lowpoly.glb')