/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import { BoardHex, HexTerrain } from '../../types'
import { hexTerrainColor } from '../maphex/hexColors'
import { Vector3 } from 'three'

const scale = new Vector3(1.02, 0.95, 1.02)

export function CastleWallEnd({ boardHex }: { boardHex: BoardHex }) {
  const { nodes } = useGLTF('/decimated-castle-wall-end.glb') as any
  const { x, z, yBase } = getBoardHex3DCoords(boardHex)
  const rotation = boardHex?.pieceRotation ?? 0
  return (
    <group >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.definitiv_wall_end.geometry}
        scale={scale}
        position={[x, yBase, z]}
        rotation={[0, rotation * -Math.PI / 3, 0]}
      >
        <meshMatcapMaterial
          color={hexTerrainColor[HexTerrain.castle]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/decimated-castle-wall-end.glb')

export function CastleWallStraight({ boardHex }: { boardHex: BoardHex }) {
  const { nodes } = useGLTF('/decimated-castle-wall-straight.glb') as any
  const { x, z, yBase } = getBoardHex3DCoords(boardHex)
  const rotation = boardHex?.pieceRotation ?? 0
  return (
    <group >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.definitiv_wall_end001.geometry}
        scale={scale}
        position={[x, yBase, z]}
        rotation={[0, rotation * -Math.PI / 3, 0]}
      >
        <meshMatcapMaterial
          color={hexTerrainColor[HexTerrain.castle]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/decimated-castle-wall-straight.glb')
