/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { PropsWithChildren } from 'react'

export function InterlockHex({ type, color, isFluid }: { type: string, color: string, isFluid?: boolean }) {
  switch (type) {
    case '0':
      return (
        <InterlockHex0>
          {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
        </InterlockHex0>
      )
    case '1':
      return (
        <InterlockHex1>
          {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
        </InterlockHex1>
      )
    // return <InterlockHex1 />
    case '2':
      return (<InterlockHex2>
        {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
      </InterlockHex2>)
    case '3':
      return (<InterlockHex3>
        {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
      </InterlockHex3>)
    case '4':
      return (<InterlockHex4>
        {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
      </InterlockHex4>)
    case '4B':
      return (<InterlockHex4B>
        {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
      </InterlockHex4B>)
    case '5':
      return (<InterlockHex5>
        {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
      </InterlockHex5>)
    case '6':
      return (<InterlockHex6>
        {isFluid ? (<meshLambertMaterial transparent opacity={0.85} color={color} />) : (<meshMatcapMaterial color={color} />)}
      </InterlockHex6>)
    default:
      return <></>
  }
}
function InterlockHex0({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-0.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock0.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-0.glb')

function InterlockHex1({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-1.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock1.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-1.glb')

function InterlockHex2({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-2.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock2.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-2.glb')

function InterlockHex3({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-3.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock3.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-3.glb')

function InterlockHex4({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-4.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock4.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-4.glb')

function InterlockHex4B({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-4B.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock4B.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-4B.glb')

function InterlockHex5({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-5.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock5.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-5.glb')

function InterlockHex6({ children }: PropsWithChildren) {
  const { nodes } = useGLTF('/interlock-hex-6.glb') as any
  return (
    < >
      <mesh
        geometry={nodes.Interlock6.geometry}
      >
        {children}
      </mesh>
    </>
  )
}
useGLTF.preload('/interlock-hex-6.glb')
