/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function InterlockHex0() {
  const { nodes } = useGLTF('/interlock-hex-0.glb') as any
  return (
    <group >
      <mesh
        geometry={nodes.Interlock0.geometry}
      />
      <meshMatcapMaterial color={'red'} />
    </group>
  )
}
useGLTF.preload('/interlock-hex-0.glb')
// useGLTF.preload('/interlock-hex-1.glb')
// useGLTF.preload('/interlock-hex-2.glb')
// useGLTF.preload('/interlock-hex-3.glb')
// useGLTF.preload('/interlock-hex-4.glb')
// useGLTF.preload('/interlock-hex-4B.glb')
// useGLTF.preload('/interlock-hex-5.glb')
// useGLTF.preload('/interlock-hex-6.glb')
