/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { BoardHex, HexTerrain } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import { hexTerrainColor } from '../maphex/hexColors'
import { HEXGRID_HEX_HEIGHT, HEXGRID_HEXCAP_HEIGHT } from '../../utils/constants'
import { getLadderBattlementOptions } from './getLadderBattlementOptions'


export function Ladder({ boardHex }: { boardHex: BoardHex }) {
  const { nodes } = useGLTF('/handmade-ladder.glb') as any
  const { x, z, y } = getBoardHex3DCoords(boardHex)
  const options = getLadderBattlementOptions(boardHex.pieceRotation)
  return (
    <group
      position={[x + options.xAdd, y - HEXGRID_HEX_HEIGHT + (HEXGRID_HEXCAP_HEIGHT / 2), z + options.zAdd]}
      rotation={[0, (boardHex.pieceRotation * -Math.PI) / 3, 0]}
    >
      <mesh
        geometry={nodes.Ladder.geometry}
      >
        <meshMatcapMaterial color={hexTerrainColor[HexTerrain.ladder]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/handmade-battlement.glb')
