/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import { BoardHex, HexTerrain } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import ObstacleBase from './ObstacleBase'
import { hexTerrainColor } from '../maphex/hexColors'

export default function LaurPillar({ boardHex, underHexTerrain }: { boardHex: BoardHex, underHexTerrain: string }) {
  const { x, z, yBaseCap, yBase } = getBoardHex3DCoords(boardHex)
  const { nodes } = useGLTF('/laurwall-pillar.glb') as any
  const rotation = boardHex?.pieceRotation ?? 0
  return (
    <group>
      <group position={[x, yBase, z]}
        rotation={[0, rotation * -Math.PI / 3, 0]}
      >
        <mesh
          geometry={nodes.LaurPillar.geometry}
        >
          <meshMatcapMaterial color={hexTerrainColor[HexTerrain.laurPillar]} />
        </mesh>
      </group>
      <ObstacleBase x={x} y={yBaseCap} z={z} color={hexTerrainColor[underHexTerrain]} />
    </group>
  )
}

useGLTF.preload('/laurwall-pillar.glb')
