/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { HexTerrain } from '../../types'
import { hexTerrainColor } from '../maphex/hexColors'

export function RoadWall() {
  const { nodes } = useGLTF('/handmade-roadwall.glb') as any
  return (
    <mesh
      geometry={nodes.RoadWall.geometry}
    >
      <meshMatcapMaterial color={hexTerrainColor[HexTerrain.roadWall]} />
    </mesh>
  )
}

useGLTF.preload('/handmade-roadwall.glb')
