/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { BoardHex } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'

export default function Ruin2({ boardHex }: { boardHex: BoardHex }) {
  const { x, y, z } = getBoardHex3DCoords(boardHex)
  const { nodes, materials } = useGLTF('/ruin2-colored-lowpoly.glb') as any
  return (
    <group position={[x, y, z]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ruin_Small_Scanned.geometry}
        material={materials.RuinGray}
        scale={0.038}
      />
    </group>
  )
}

useGLTF.preload('/ruin2-colored-lowpoly.glb')
