/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import { BoardHex } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'

export default function TicallaBrush({ boardHex }: { boardHex: BoardHex }) {
  const { x, y, z } = getBoardHex3DCoords(boardHex)
  const { nodes, materials } = useGLTF('/ticalla-brush-colored-lowpoly.glb') as any
  return (
    <group position={[x, y, z]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlankFern1_1.geometry}
        material={materials.BushFern}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlankFern1_2.geometry}
        material={materials.PalmBush}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlankFern1_3.geometry}
        material={materials.BushArbol}
      />
    </group>
  )
}

useGLTF.preload('/ticalla-brush-colored-lowpoly.glb')
