/*
Auto-generated by: https://github.com/pmndrs/gltfjsx @ https://gltf.pmnd.rs/
*/

import { useGLTF } from '@react-three/drei'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import { HEXGRID_HEXCAP_HEIGHT } from '../../utils/constants'
import { BoardHex, HexTerrain } from '../../types'
import { hexTerrainColor } from '../maphex/hexColors'
import ObstacleBase from './ObstacleBase'

export default function TicallaPalm({ boardHex }: { boardHex: BoardHex }) {
  const { nodes,
    // materials
  } = useGLTF('/ticalla-palm-colored-lowpoly.glb') as any
  const { x, y, z } = getBoardHex3DCoords(boardHex)
  const yTree = y + HEXGRID_HEXCAP_HEIGHT / 2
  const yBase = y + HEXGRID_HEXCAP_HEIGHT / 2
  // const y = (boardHex.altitude - 1) * HEXGRID_HEX_HEIGHT
  // const yTree = y + HEXGRID_HEX_HEIGHT
  const options = getOptionsForTreeHeight(boardHex?.obstacleHeight ?? 14)
  const rotation = boardHex?.pieceRotation ?? 0
  function getOptionsForTreeHeight(height: number) {
    switch (height) {
      case 14:
        return { scaleX: 0.038, scaleY: 0.046 }
      case 15:
        return { scaleX: 0.038, scaleY: 0.042 }
      case 16:
      default:
        return { scaleX: 0.038, scaleY: 0.038 }
    }
  }
  return (
    <group>
      <group
        scale={[options.scaleX, options.scaleY, options.scaleX]}
        position={[x, yTree, z]}
        rotation={[0, rotation * -Math.PI / 3, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AlienGrassUFO_v01_Tuft_a_1.geometry}
        // material={materials.PalmGrass}
        >
          <meshMatcapMaterial color={'#A9E718'} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AlienGrassUFO_v01_Tuft_a_2.geometry}
        // material={materials.PalmTrunk}
        >
          <meshMatcapMaterial color={'#E77D2D'} />

        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AlienGrassUFO_v01_Tuft_a_3.geometry}
        // material={materials.PalmLeaf}
        >
          <meshMatcapMaterial color={'#35E718'} />

        </mesh>
      </group>
      <ObstacleBase x={x} y={yBase} z={z} color={hexTerrainColor[HexTerrain.palm]} />
    </group>
  )
}

useGLTF.preload('/ticalla-palm-colored-lowpoly.glb')
