/*
Auto-generated by: https://github.com/pmndrs/gltfjsx @ https://gltf.pmnd.rs/
*/

import { useGLTF } from '@react-three/drei'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import { TREE_BASE_HEIGHT } from '../../utils/constants'
import { BoardHex, HexTerrain } from '../../types'
import { hexTerrainColor } from '../maphex/hexColors'
import ObstacleBase from './ObstacleBase'

export default function TicallaPalm({ boardHex }: { boardHex: BoardHex }) {
  const { nodes, materials } = useGLTF('/ticalla-palm-colored-lowpoly.glb') as any
  const { x, y, z } = getBoardHex3DCoords(boardHex)
  const yTree = y + TREE_BASE_HEIGHT / 2
  const yBase = y + TREE_BASE_HEIGHT / 2
  // const y = (boardHex.altitude - 1) * HEXGRID_HEX_HEIGHT
  // const yTree = y + HEXGRID_HEX_HEIGHT
  const options = getOptionsForTreeHeight(boardHex?.obstacleHeight ?? 14)
  function getOptionsForTreeHeight(height: number) {
    switch (height) {
      case 14:
        return { scaleX: 0.038, scaleY: 0.046 }
      case 15:
        return { scaleX: 0.038, scaleY: 0.042 }
      case 16:
      default:
        return { scaleX: 0.038, scaleY: 0.038 }
    }
  }
  return (
    <group>
      <group
        scale={[options.scaleX, options.scaleY, options.scaleX]}
        position={[x, yTree, z]}
        dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AlienGrassUFO_v01_Tuft_a_1.geometry}
          material={materials.PalmGrass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AlienGrassUFO_v01_Tuft_a_2.geometry}
          material={materials.PalmTrunk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AlienGrassUFO_v01_Tuft_a_3.geometry}
          material={materials.PalmLeaf}
        />
      </group>
      <ObstacleBase x={x} y={yBase} z={z} color={hexTerrainColor[HexTerrain.palm]} />
    </group>
  )
}

useGLTF.preload('/ticalla-palm-colored-lowpoly.glb')
