/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { BoardHex } from '../../types'
import { getBoardHex3DCoords } from '../../utils/map-utils'
import { HEXGRID_HEX_HEIGHT } from '../../utils/constants'

export function Tree10ColoredLowPoly({ boardHex }: { boardHex: BoardHex }) {
  const { x, y, z } = getBoardHex3DCoords(boardHex)
  const { nodes, materials } = useGLTF('/forgotten-forest-tree-low-poly-colored.glb') as any
  return (
    <group
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree10_scanned.geometry}
        material={materials.ForestTree}
        scale={0.040}
        position={[x, y - HEXGRID_HEX_HEIGHT, z]}
      // rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/forgotten-forest-tree-low-poly-colored.glb')